### ISSUE TITLE
Add validation feature for the patient registration form

### ISSUE THREAD

**Issue by siv2r** [siv2r/kidney-exchange#1]
Ex: like the name field should not be left empty by the user

![form-validation](https://user-images.githubusercontent.com/56887198/94822042-de990680-041f-11eb-9039-5f276eb1978a.png)

**Comment by amitagarwalaa57** [comment]
Assign me the task.

**Comment by siv2r** [comment]
Please use the jQuery validation plugin. Also, add the validation function in scripts/reg-form.js not in scripts/validate.js

**Comment by karmakula** [comment]
would love to give this a try, if you dont mind

**Comment by siv2r** [comment]
Sure, go ahead!

**Comment by siv2r** [comment]
This issue has been resolved
