### ISSUE TITLE
[Gssoc'21] back to top button

### ISSUE THREAD

**Issue by arpit456jain** [siv2r/kidney-exchange#100]
I would like to add a back to top button with smooth scrolling

**Comment by siv2r** [comment]
Where would you like to add them? Please be specific.

**Comment by arpit456jain** [comment]
> Where would you like to add them? Please be specific.

On main page.

**Comment by siv2r** [comment]
There is no content on the main page so, this will not be useful

You can maybe try adding them on form pages

**Comment by arpit456jain** [comment]
> There is no content on the main page so, this will not be useful
> 
> You can maybe try adding them on form pages

@siv2r login and sign up page?

**Comment by siv2r** [comment]
@arpit456jain How will it be useful? They are small already right?

**Comment by arpit456jain** [comment]
> @arpit456jain How will it be useful? They already fit in a single page right?

Yes that's why i put a question mark 😅

Actually you asked to put back to top button on form pages which i don't understand

**Comment by siv2r** [comment]
:+1: I don't think the back-to-top button will be super useful for this website. Other than the form pages all other pages fit in a single page perfectly.

>Actually you asked to put back to top button on form pages which i don't understand

There is very little documentation for this project which make it difficult for new contributors :(
You can try to read code and understand and you can always ask your doubts by opening an issue here on GitHub or on discord :)

**Comment by arpit456jain** [comment]
So can i close this issue?
