### ISSUE TITLE
[Gssoc'21] Responsiveness of Login page

### ISSUE THREAD

**Issue by arpit456jain** [siv2r/kidney-exchange#101]
The login page is not good for mobile view and its not responsive at all.
<img width="960" alt="po" src="https://user-images.githubusercontent.com/55352601/114128997-4eca9c80-991b-11eb-9eed-11d97e960e74.png">

I would like to make it responsive as much as possible.

**Comment by siv2r** [comment]
Every page is not responsive. You take a look at #22 for more info.

**Comment by arpit456jain** [comment]
Yes @siv2r if you want i can try to make them all responsive as much as possible.

**Comment by siv2r** [comment]
Sure!
How do you plan on doing? Using CSS?

**Comment by arpit456jain** [comment]
2 ways 
1 i can try to add some bootstrap classes 
2 write css in media queries for small screen

I will try 1 option first if it not work then i will go for 2nd

**Comment by arpit456jain** [comment]
@siv2r kindly merge my pr for show password so i can start work on this issue as i am not very much comfortable in working on multiple branches

**Comment by siv2r** [comment]
> @siv2r kindly merge my pr for show password so i can start work on this issue as i am not very much comfortable in working on multiple branches

You can work on different issues by creating a new branch for each one of them. I don't understand how the branch for show password issue affects this? since Ideally the show password branch will be deleted after merging.

**Comment by arpit456jain** [comment]
> > @siv2r kindly merge my pr for show password so i can start work on this issue as i am not very much comfortable in working on multiple branches
> 
> You can work on different issues by creating a new branch for each one of them. I don't understand how the branch for show password issue affects this? since Ideally the show password branch will be deleted after merging.

Actually last time when I worked on multiple branches in a project some conflicts occur that's why i avoid to work on multiple branch.
I prefer to work on one branch at a time 😅

**Comment by arpit456jain** [comment]
@siv2r i would like to work on this issue but the problem is phpfmt is still not working in my vs code

**Comment by siv2r** [comment]
You can look into `phpfmt` after you finish the PR since it is used only for formatting. Then we can discuss an alternative to `phpfmt` if required :)

**Comment by arpit456jain** [comment]
Ok

**Comment by arpit456jain** [comment]
@siv2r can you provide me a db file for this project to i can import that file into my db so all the tables create automatically

bacuase I had made the login / sign up and home page responsive but the navbar is not working properly and its not responsive also and for that i have to login
