### ISSUE TITLE
Footer Missing on Home Page

### ISSUE THREAD

**Issue by hardikvarshney** [siv2r/kidney-exchange#104]

**Comment by hardikvarshney** [comment]
I will make responsive footer for the website.

**Comment by siv2r** [comment]
Also, add some details to the description of this issue so, that I can know what you want to do exactly :)

**Comment by hardikvarshney** [comment]
It would be a simple footer with element such as "follow us" (on which github repository link will be there). "Brand logo" will be there(by clicking on it user will be redirected to home page) and lastly  "copyright information" will be their.
If you have any other idea you can give...

**Comment by siv2r** [comment]
Sounds good!

**Comment by hardikvarshney** [comment]
So, please assign this issue to me.

**Comment by hardikvarshney** [comment]
Level of issue...????

**Comment by siv2r** [comment]
> Level of issue...????

I will assign it to the PR depending on its content. For now, just focus on implementing the changes. We can always assign/change labels as required.

**Comment by hardikvarshney** [comment]
Okay.

**Comment by hardikvarshney** [comment]
This is the footer I have designed.
![Screenshot (81)](https://user-images.githubusercontent.com/76947310/114294640-a274eb80-9abd-11eb-8164-c8294f65d187.png)

**Comment by hardikvarshney** [comment]
@siv2r please review it.

**Comment by siv2r** [comment]
Hey, I will review it soon (today/tommorow). Thanks for the reminder.

**Comment by hardikvarshney** [comment]
> Hey, I will review it soon (today/tommorow). Thanks for the reminder.

Okay

**Comment by hardikvarshney** [comment]
@siv2r  One more thing I want to bring to your notice that "Prince-yohannan" has made a PR for the issue which was assigned to me(issue#104  : Footer Missing). Neither he opened the issue nor he was assigned. So, kindly ask him not to do so.

**Comment by hardikvarshney** [comment]
> @siv2r One more thing I want to bring to your notice that "Prince-yohannan" has made a PR for the issue which was assigned to me(issue#104 : Footer Missing). Neither he opened the issue nor he was assigned. So, kindly ask him not to do so.

@siv2r Kindly review it.

**Comment by siv2r** [comment]
@hardikvarshney I think it will be better if the logo and copyright are side by side instead of vertical aligned.

Also, create a PR for this. It will be better to discuss the PR since I can see your code there.

**Comment by hardikvarshney** [comment]
Okay, I will create PR for this.

**Comment by siv2r** [comment]
Hey, why was this issue closed?

**Comment by siv2r** [comment]
Reopening the issue since it was not resolved.

**Comment by siv2r** [comment]
@hardikvarshney did u get a chance to create a PR for this issue?

**Comment by hardikvarshney** [comment]
@siv2r Currently I am busy with  my mid semester exams. Soon I will be creating PR for this issue.

**Comment by siv2r** [comment]
Sure, no worries. I just wanted to confirm it. Take your time to send the PR. 
All the best for your exams!

**Comment by SpecTEviL** [comment]
@siv2r If you don't mind can I work on this?

**Comment by priyanshuone6** [comment]
@hardikvarshney are you working on this?

**Comment by SpecTEviL** [comment]
> @hardikvarshney are you working on this?

It's been more than 12 days and I think that's more than enough for this issue. If you don't mind can I take it up? I can finish it by tomorrow.

**Comment by priyanshuone6** [comment]
@SpecTEviL please wait for his reply by today, if he doesn't, this issue will be assigned to you

**Comment by priyanshuone6** [comment]
@SpecTEviL go ahead

**Comment by arpit456jain** [comment]
Hey i am also interested in this issue

**Comment by arpit456jain** [comment]
Hey @SpecTEviL if you are working on this try to make a responsive footer using bootstrap.
But please let me know whether you are working on it or not

**Comment by SpecTEviL** [comment]
Yes i'm working. I'll update you by tomorrow. And also i'll use bootstrap now.

**Comment by arpit456jain** [comment]
@SpecTEviL any update ?? 
See actually i am working on responsiveness of the website that's why i need at least a basic layout of footer so that i can adjust it if its creating any mes because there are chances that the class you use in css for footer may be overwrite by internal css .
@priyanshuone6 @siv2r please look into this.
