### ISSUE TITLE
Create a step by step docs for new contributors

### ISSUE THREAD

**Issue by siv2r** [siv2r/kidney-exchange#112]
Many new contributors are unable to submit their first PR due to a lack of info. I want a document that a new contributor can follow exactly to submit his/her first PR.

I want this documentation to be of high quality so, do not take this issue for the sake of points in GSSoC. 

**Information that needs to be present**
1. Introduction in the discord group
2. Find a new issue 
3. Get help from the community
4. Fork the repo
5. Make your changes
6. Push your changes to the forked repo
7. Create your first pull request
8. Get feedback from the mentors
9. Go to step 5 again

**Comment by Sukriti-sood** [comment]
I would like to work on This

**Comment by priyanshuone6** [comment]
@Sukriti-sood Sure, go ahead!

**Comment by siv2r** [comment]
@Sukriti-sood feel free ask for any help/doubts in our discord groups :)
