### ISSUE TITLE
Replace the PR template with a new one

### ISSUE THREAD

**Issue by siv2r** [siv2r/kidney-exchange#124]
[This](https://www.github.com/theos/theos/tree/master/.github%2FPULL_REQUEST_TEMPLATE.md) is the PR template of Theo's project. We can use the same since this project also uses theo's issue template.

Take ideas from [pybamm](https://github.com/pybamm-team/PyBaMM/blob/develop/.github/PULL_REQUEST_TEMPLATE.md), [oppia](https://github.com/oppia/oppia/blob/develop/.github/PULL_REQUEST_TEMPLATE.md).

**Comment by priyanshuone6** [comment]
Take ideas from [pybamm](https://github.com/pybamm-team/PyBaMM/blob/develop/.github/PULL_REQUEST_TEMPLATE.md), [oppia](https://github.com/oppia/oppia/blob/develop/.github/PULL_REQUEST_TEMPLATE.md).

**Comment by siv2r** [comment]
@priyanshuone6 are you able to edit the description of this issue? If so, you can add it there

**Comment by darpankhanna** [comment]
@siv2r can u assign me this issue?

**Comment by siv2r** [comment]
Closing since #139 fixes this
