### ISSUE TITLE
Navbar is creating problem on every page

### ISSUE THREAD

**Issue by arpit456jain** [siv2r/kidney-exchange#125]
What are the steps to reproduce this issue?

Navbar is not responsive at all 

What were you expecting to happen?
It should be compatible ein small screens

Any other comments?
Well its not suitable to make it responsive instead of this i can replace it with bootstrap navbar . of course it needed  a lot of Css to make it like current navbar but at least it will be responsive and better .

Note : I will be needed a db file for making tables in phpmyadmin

**Comment by siv2r** [comment]
Hey, see #22 
This issue is the same as that. We can have the future discussions in that issue

**Comment by siv2r** [comment]
closing this issue since this is a duplicate
