### ISSUE TITLE
Replace the link of slack group with the discord group link on the Readme

### ISSUE THREAD

**Issue by siv2r** [siv2r/kidney-exchange#132]

**Comment by Spurthi7768** [comment]
@siv2r  Can you assign this issue to me ? Also the link of discord group?

**Comment by priyanshuone6** [comment]
@Spurthi7768 Sure, can you also submit a PR with the things mentioned in the 4th point [here](https://github.com/siv2r/kidney-exchange/issues/26#issue-771537125).
