### ISSUE TITLE
Welcome bot features

### ISSUE THREAD

**Issue by siv2r** [siv2r/kidney-exchange#142]
welcome bot message:
1. mention guidelines
2. mention the creating your first PR doc (#112)

**Comment by Sukriti-sood** [comment]
I want to work on this ,

**Comment by siv2r** [comment]
Please consider working on one issue at a time. I will assign this issue to you later.
Also, don't worry about other contributors working; taking up this issue before you since you can always collaborate.

**Comment by arpit456jain** [comment]
hey @siv2r currently i am free and wiling to work on this issue .

**Comment by arpit456jain** [comment]
<img width="960" alt="github bot" src="https://user-images.githubusercontent.com/55352601/117988884-72896400-b359-11eb-9f14-301f857bcc38.png">

It will look some thing like this @siv2r  is it fine ??

**Comment by siv2r** [comment]
Instead of the `To get assigned to this particular issue,` you can put `You can start working on the issue. Don't wait for it to be assigned.`

**Comment by siv2r** [comment]
@Sukriti-sood @priyanshuone6 @riasenpai If you have any suggestions for the welcome message. Please pitch in.

**Comment by priyanshuone6** [comment]
Also add something like just drop a comment to let others know that you are working on this issue

**Comment by arpit456jain** [comment]
> Also add something like just drop a comment to let others know that you are working on this issue

If i change the msg to start working don't wait for assigning then it already means i am working on it 😅 isn't?

**Comment by arpit456jain** [comment]
> Also add something like just drop a comment to let others know that you are working on this issue

And for this we are assigned to work 🤔

**Comment by priyanshuone6** [comment]
I meant something like leaving a comment that says that I have started working on this, so that it won't create a conflict between two people trying to work on the same issue

**Comment by arpit456jain** [comment]
> I meant something like leaving a comment that says that I have started working on this, so that it won't create a conflict between two people trying to work on the same issue

Yeah got it i have a idea suitable for this but i am not sure it will work not. 
Lets see ...
Will update you soon :)

**Comment by Sukriti-sood** [comment]
@siv2r @priyanshuone6 I was confused with all conversation , If you thnk I should not Created a PR , You can close it.

**Comment by priyanshuone6** [comment]
@arpit456jain @Sukriti-sood both are working on the same issue, I think @arpit456jain is already assigned to this

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/118077268-693bde00-b3d1-11eb-9bdc-179d7d1458c7.mp4

@priyanshuone6 @siv2r how 's this . let me explain  what I did.
Firstly user will create a issue , I have used your issue template that's why its adding bug label .
Then bot will greet (Ignore the msg i will change it when creating  a PR) 

Then Most important part any one can assign themselves by commenting **/assign**
I can add a line in greeting that **please comment /assign to assign it to you**

**Comment by arpit456jain** [comment]
Is it possible that first you merge @Sukriti-sood PR and then my PR too because i had no intentions of stoleing her points .
We can do one thing her msg is pretty good after merging her PR i will rebase my code and will add that auto assign feature

**Comment by siv2r** [comment]
@Sukriti-sood, your bot looks really good in aesthetics, and @arpit456jain has a good message. A combination of both will be great!

**Comment by siv2r** [comment]
@arpit456jain are you able to edit @Sukriti-sood PR? If so, I think both of you will co-author for the PR, and points will go to both.

**Comment by arpit456jain** [comment]
> @arpit456jain are you able to edit @Sukriti-sood PR? If so, I think both of you will co-author for the PR, and points will go to both.
> I can confirm this with the girl script team regarding points allocated for co-authors of a PR.
> If not, @Sukriti-sood please give permissions for arpit to edit.

I am not sure @siv2r . never done that before . Her bots really good I suggest to merge her PR then i will try to add my feature if it works well n good ,  i will create a PR otherwise no problem the main task is already competed  :)

**Comment by arpit456jain** [comment]
More than 1 one PR can be merged for 1 issue no problem in that . But at least we have our separate PR's if in case any problem occurs you can easily revert the PR

**Comment by siv2r** [comment]
@Sukriti-sood, does the welcome bot responds to first-timers only? Since #150 does seem to get any message.

**Comment by Sukriti-sood** [comment]
> @Sukriti-sood, does the welcome bot responds to first-timers only? Since #150 does seem to get any message.
Ya , Welcome Bot means same for first time contributors ,If you want for Every Issue and PR Open and PR merge , I will do that.

**Comment by Sukriti-sood** [comment]
> > @Sukriti-sood, does the welcome bot responds to first-timers only? Since #150 does seem to get any message.
> > 
Ya , Welcome Bot means same for first time contributors ,If you want for Every Issue and PR Open and PR merge , I will do that.

**Comment by siv2r** [comment]
No need. I just wanted to confirm. It is unnecessary for every issue.

**Comment by arpit456jain** [comment]
Hey @siv2r please close this issue both PRs got merged :)

**Comment by siv2r** [comment]
we can use this to track new features for welcomes bot.

**Comment by priyanshuone6** [comment]
@arpit456jain Could you please remove the link embedded in the `has been assigned` comment when someone comments `\assign` as the link doesn't make any sense

**Comment by arpit456jain** [comment]
> @arpit456jain Could you please remove the link embedded in the `has been assigned` comment when someone comments `\assign` as the link doesn't make any sense

@priyanshuone6 I don't think so because that code is just like a API it is fetching a pre written code .  I had not written that msg from myself 😅.

**Comment by priyanshuone6** [comment]
@arpit456jain I think there is an option to customize the message, please see
https://github.com/JasonEtco/slash-assign-action#assigned_comment

You have to add a `assigned_comment` property with the comment under the with

**Comment by arpit456jain** [comment]
Ok i will try this for sure
