### ISSUE TITLE
Responsiveness of Overview Page

### ISSUE THREAD

**Issue by arpit456jain** [siv2r/kidney-exchange#155]
Responsiveness of Overview Page

**Comment by arpit456jain** [comment]
![screencapture-localhost-kidney-exchange-pages-dataOverview-php-2021-05-14-18_58_30](https://user-images.githubusercontent.com/55352601/118277425-6848a080-b4e6-11eb-87a9-8d05992c56aa.png)
![screencapture-localhost-kidney-exchange-pages-dataOverview-php-2021-05-14-18_57_25](https://user-images.githubusercontent.com/55352601/118277441-6b439100-b4e6-11eb-8da5-fc0207bf8c4c.png)

**Comment by arpit456jain** [comment]
@siv2r Please select one of these first one is having little bit small font user must have to zoom a litle bit
2nd one is optimized font size but it is taking 2 lines

**Comment by siv2r** [comment]
@arpit456jain, the 2nd one is good. The bigger font with two lines.

**Comment by arpit456jain** [comment]
Ok @siv2r will make a PR for this soon 
Kindly add label of level my previous PR

**Comment by siv2r** [comment]
> Kindly add label of level my previous PR

I added it. The width bug PR right?

**Comment by arpit456jain** [comment]
yes thanks :)

**Comment by arpit456jain** [comment]
making a PR for this issue

**Comment by arpit456jain** [comment]
@siv2r kindly review my PR
