### ISSUE TITLE
Remove huge code comments

### ISSUE THREAD

**Issue by siv2r** [siv2r/kidney-exchange#158]
- some of the commented code has a considerable size. It would be nice to remove it altogether.
For Example https://github.com/siv2r/kidney-exchange/blob/master/functions/json.func.php#L47-L91

Find similar ones like the example above and remove them.

**Comment by arpit456jain** [comment]
@siv2r from all files ??

**Comment by siv2r** [comment]
> @siv2r from all files ??

Yes. Only remove the comments that are large(say 7+ lines).

**Comment by arpit456jain** [comment]
Please review my PR

**Comment by Itashamodi** [comment]
assign it to me

**Comment by riasenpai** [comment]
@siv2r  I dont think comment codes are still remaining that are very large. Do we still keep the issue open?

**Comment by siv2r** [comment]
Thanks for the heads-up! 
@riasenpai I haven't checked the files. I will check them later and close this issue if needed. 
If you have checked the files already, then you can close it.
