### ISSUE TITLE
Use GitHub Project Boards, to track features, instead of Readme

### ISSUE THREAD

**Issue by siv2r** [siv2r/kidney-exchange#159]
Currently, the scoring functions used are tracked in a readme file. See here: https://github.com/siv2r/kidney-exchange/blob/master/functions/scoringFunctions.md.

It would great if we could do these using GitHub project boards.

**Comment by AshuKV** [comment]
Hi I am a GSSOC'21 participant. I want to work on this issue under GSSoC'21. Can you please assign it to me?

**Comment by subhangi2731** [comment]
@siv2r please assign this issue to me
