### ISSUE TITLE
Create a document for setting up this project

### ISSUE THREAD

**Issue by siv2r** [siv2r/kidney-exchange#164]
Currently, this project has information about the project set up embedded in its [readme](https://github.com/siv2r/kidney-exchange#setting-up-this-project).

It would be nice if there is a separate document for this, and we can include this under the [documentation subsection of the readme](https://github.com/siv2r/kidney-exchange#documentation).

This is essential documentation so, make sure your PR is of good quality.

**Comment by subhangi2731** [comment]
@siv2r please let me work on this too

**Comment by AshuKV** [comment]
Hi I am a GSSOC'21 participant. I want to work on this issue under GSSoC'21. Can you please assign it to me?

**Comment by siv2r** [comment]
@AshuKV consider working on one issue at a time. I have assigned you
