### ISSUE TITLE
footer in pairwisematch.php must be  at bottom

### ISSUE THREAD

**Issue by arpit456jain** [siv2r/kidney-exchange#188]
footer in pairwisematch.php must be  at bottom
<img width="960" alt="sss" src="https://user-images.githubusercontent.com/55352601/118750749-a72b7d00-b87d-11eb-96b2-730e5637a992.png">

**Comment by siv2r** [comment]
@arpit456jain so, is it required to adjust the footer for every single page?

**Comment by arpit456jain** [comment]
> @arpit456jain so, is it required to adjust the footer for every single page?

@siv2r only on those pages on which the content is less .
Like when there is no content on home page the footer comes to close to navbar that's why I have to add some content.
So if the content on the Page after navbar is not covering whole page then i have to add some more margin and paddig so that footer can go to bottom
