### ISSUE TITLE
Template for Feature Request

### ISSUE THREAD

**Issue by darpankhanna** [siv2r/kidney-exchange#197]
Contributors who want to improve or give suggestions for the documentation of Readme can use this template.

**Comment by darpankhanna** [comment]
@siv2r Can u assign me this issue?

**Comment by siv2r** [comment]
@darpankhanna this seems to be a very specific problem so, the template for it will not be useful. 
You could try changing this to a **Template for Feature Request**. This is kind of template will be useful

**Comment by madihamallick** [comment]
@siv2r Please assign this to me

**Comment by siv2r** [comment]
This issue has been resolved
