### ISSUE TITLE
Store the data entered by the user in a database

### ISSUE THREAD

**Issue by siv2r** [siv2r/kidney-exchange#2]
You can do the following two things:
1. Add a new process.php file which the form in register_patient.php can redirect to
2. Add the PHP code at the top of the register_patient.php file

**Comment by cobasesp** [comment]
Hi! can you assign this to me?

**Comment by siv2r** [comment]
@cobasesp I will update the details about the structure of the database (like no of tables etc) soon. Till then go through the register_patient.php file which stores user details in the database for the previous version of the registration form.
