### ISSUE TITLE
Modularize the codebase

### ISSUE THREAD

**Issue by siv2r** [siv2r/kidney-exchange#23]
This can be worked on once the issue #24 is resolved.

Soln idea:
- separate ccs code in PHP files to a new file.
- use a single validation js file instead of two js files performing the same validation (reg-form.js and editPairForm.js)
- maybe separate each form element??

Take look at the architecture branch for more info.

**Comment by siv2r** [comment]
@subhangi2731 sorry for the late reply. Do let me know if you are still interested in working on this issue :)

**Comment by siv2r** [comment]
Feel free to ask ANY doubts in the discord grp of this project

**Comment by subhangi2731** [comment]
Yes i am interested please assign me

**Comment by arpit456jain** [comment]
hey @subhangi2731 just comment "/assign"  without these double quotes this issue will be assigned to you by the bot .
you can start start working on it  no need for waiting  :)
