### ISSUE TITLE
Include new discord server link in readme

### ISSUE THREAD

**Issue by siv2r** [siv2r/kidney-exchange#240]
### Can you please describe the problem to be solved?
New discord server link to be added in the readme file of the repo since, girlscript will delete their server after the program ends.

### Can you give some suggestions?

Just replace the previous discord server link in the readme with this: https://discord.gg/uH35zjW5cN

**Comment by madihamallick** [comment]
@siv2r Please assign this to me

**Comment by tech-rounak** [comment]
hey sir can  I contribute

**Comment by siv2r** [comment]
@tech-rounak this issue has been resolved already. You can take a look at other `good-first-issue` to get started :)

**Comment by siv2r** [comment]
Closing the issue since, it has been resolved already
