### ISSUE TITLE
Change the url's path in the nav bar

### ISSUE THREAD

**Issue by siv2r** [siv2r/kidney-exchange#25]
**Note:** The changes must be implemented in the `architecture` branch, not on the `master`

[ ] remove `subpagesNavBar.php` and maintain a single file for the navbar.

Note: use '/' at the start for the relative root path

**Comment by sahilempire** [comment]
I want to work on this issue, Please **assign me**.

Thank you.

**Comment by siv2r** [comment]
@sahilempire Sure!! Go ahead 👍

**Comment by sahildotexe** [comment]
Hey !! I am a participant of GSSOC'21 , can you assign this issue to me?

**Comment by lakshita15** [comment]
I'am gssoc participant 
I would like to work on this issue. I will submit before due date with fantastic work.

**Comment by siv2r** [comment]
@lakshita15, consider working on one issue at a time. You can always move on to another later :)

**Comment by siv2r** [comment]
Closing it since this is a duplicate of #24
