### ISSUE TITLE
add little changes in project Overview context section add line height so that font looks nice.

### ISSUE THREAD

**Issue by starrohan999** [siv2r/kidney-exchange#283]
### Can you please describe the problem to be solved?
add little changes in the project Overview context section add line height so that font looks nice. and easy to read 

### Can you give some suggestions?
By adding a line height in CSS code we can make it pleasant.

**Comment by starrohan999** [comment]
Hii @siv2r 
I am an LGM-S0C-21 participant please assign it to me.

**Comment by siv2r** [comment]
@starrohan999 
#280 has been merged now, which changes the overview section. Do consider it while you make your changes.

**Comment by starrohan999** [comment]
I think all things are solved in that Pr. and line-height is also good.

Please close the issue 
I will look upto new issues and bug

**Comment by siv2r** [comment]
@starrohan999 Sure!
