### ISSUE TITLE
Adding contact page

### ISSUE THREAD

**Issue by PranavChauhan22** [siv2r/kidney-exchange#284]
### Can you please describe the problem to be solved?
I want to add contact us page which is the necessary section as website is concerned about healthcare.

### Can you give some suggestions?
I will add a new contact page which will be dynamic and contains all info regarding mentors.

Please assign me this issue under lgm-soc participant

**Comment by siv2r** [comment]
@PranavChauhan22 Do you plan on adding the details of mentors to the website? I don't think that will be necessary since they are mentoring this under the LGM-SOC program, and doctors will use this website. So it would of no use for the doctors to contact these mentors.
