### ISSUE TITLE
Make login and sign-up page completely responsive

### ISSUE THREAD

**Issue by priyaastha** [siv2r/kidney-exchange#286]
### Can you please describe the problem to be solved?

I want to make the login and signup pages completely responsive.

### Can you give some suggestions?

Making the pages responsive will make the website easier to be used on any device. 
Assign me this issue under LGM SOC'21.

If there are multiple solutions, please present each one separately.

Save comparisons for the very end.

**Comment by siv2r** [comment]
@priyaastha Aren't those pages already responsive? Which problem did you notice? A screenshot of it will be helpful!

**Comment by siv2r** [comment]
@priyaastha, feel free to ask for doubts on the discord server! The community is pretty active :)
