### ISSUE TITLE
Add donate button

### ISSUE THREAD

**Issue by vimalprogrammer** [siv2r/kidney-exchange#288]
Add Razorpay donate button in the header...

I would to like work on this issue under LGMSOC, please assign me...

**Comment by riasenpai** [comment]
Admin will review this issue since I am not sure if there is a need of donate button.

**Comment by siv2r** [comment]
@vimalprogrammer I am not sure if a donate button is required right now. 
Can you elaborate on the idea? Can you show some examples that you plan to refer to?

**Comment by vimalprogrammer** [comment]
> @vimalprogrammer I am not sure if a donate button is required right now.
> Can you elaborate on the idea? Can you show some examples that you plan to refer to?

Yeah! you know someone who does not afford to give a kidney, but they likely thought to help us. So it is a better way to raise some fundraising and help the needed one's. But it's not fully responsible. 
<h2>References below</h2>

![39322_Importance20of20a20Great20Donate20Button20banner20blog20header-7](https://user-images.githubusercontent.com/76787061/121681974-18ef9300-cad9-11eb-864a-8d3c204df571.jpg)
![donate-button-banner](https://user-images.githubusercontent.com/76787061/121681982-1a20c000-cad9-11eb-9b71-f7004f542869.jpg)

Admin's if you think it'll be a good idea assign me, otherwise no problem I love to contribute in other ways : )

**Comment by siv2r** [comment]
@vimalprogrammer I don't think it is required right now since this will clutter the nav bar. However, I will keep this issue open since we may need this in the future.

**Comment by vimalprogrammer** [comment]
> @vimalprogrammer I don't think it is required right now since this will clutter the nav bar. However, I will keep this issue open since we may need this in the future.

yeah! that's completely fine...👍
