### ISSUE TITLE
Make validation of address on forms loose

### ISSUE THREAD

**Issue by siv2r** [siv2r/kidney-exchange#29]
**Changes Required**
- allow any character for addr line 1
- allow spaces for city

The validations applied during patient registration can be found [here](https://github.com/siv2r/kidney-exchange/blob/master/js/reg-form.js#L239-L283)
The validations applied during editing the patient data can be found [here](https://github.com/siv2r/kidney-exchange/blob/master/js/editPairForm.js#L243-L297)

**Comment by Spurthi7768** [comment]
@siv2r Can you assign this issue to me? I am a participant at GSSOC and I want to contribute in solving this issue.

**Comment by siv2r** [comment]
@Spurthi7768 Sure, go ahead! I have also added some additional info in the description :)

**Comment by Spurthi7768** [comment]
@siv2r  Thanks! But I am unable to fork the repo can you suggest something?

**Comment by Spurthi7768** [comment]
@siv2r I have created a pull request for this issue. Can you please go through it and let me know any further changes are required it or not? Also, can I know what is your name on discord of GSSOC?

**Comment by araiz-1999** [comment]
Will like to work on this issue...

**Comment by kumarshobhit** [comment]
I would like to work on this issue

**Comment by kumarshobhit** [comment]
I am a LGM-SOC participant

**Comment by siv2r** [comment]
@kumarshobhit sure! Go ahead.
You can ask your doubts in the community fiscord server (mentioned in Readme).

**Comment by kumarshobhit** [comment]
sure :)
