### ISSUE TITLE
Want to add Contribution Guidelines in Readme File

### ISSUE THREAD

**Issue by Shaishav0507** [siv2r/kidney-exchange#299]
Hey @siv2r 
I would like to add contribution guidelines to the readme file.
Please assign it to me.
Thanks.

### Can you give some suggestions?

If there are multiple solutions, please present each one separately.

Save comparisons for the very end.

**Comment by siv2r** [comment]
@Shaishav0507 Sure, go ahead!

There is already an implementation of this here: https://github.com/siv2r/kidney-exchange/blob/master/docs/CONTRIBUTING.md#general-guidelines.

You can try to improve upon it or create a new doc dedicated to only guidelines. Note: If you plan to create a new doc, make sure that you include all the information provided in the above doc.

**Comment by siv2r** [comment]
Also, feel free to ask for doubts in the community discord server :)

**Comment by Shaishav0507** [comment]
Sure
