### ISSUE TITLE
About Page can be added.

### ISSUE THREAD

**Issue by jugeshraghav** [siv2r/kidney-exchange#304]

**Comment by jugeshraghav** [comment]
please assign this issue to me @siv2r

**Comment by siv2r** [comment]
> please assign this issue to me @siv2r 

You are already assigned. 

What to plan to add in the about page? Will it be included in the website? Or is it a technical documentation?

**Comment by jugeshraghav** [comment]
Yes I was thinking to add an about page which will include the details of the kidney exchange program mission . And some other brief details about the past accomplishments.   
If you could suggest me some points to include in the about page. @siv2r

**Comment by jugeshraghav** [comment]
If  the issue is assigned to me then why is there no label ??

**Comment by siv2r** [comment]
Check the assignee's section. The label section is for `LGMSOC21`, `Level1`
etc. I am sure this issue is assigned to you.

**Comment by siv2r** [comment]
@jugeshraghav This about page would be better if it was a document on this repo instead of a new page on the website.  Adding additional pages will clutter the navbar. Also, the homepage of the website gives a brief overview of the project, which will suffice.

**Comment by jugeshraghav** [comment]
Okay then I will make it as a document .

**Comment by siv2r** [comment]
> Okay then I will make it as a document .

Awesome! Feel free to ask for doubts/help in the discord server

**Comment by jugeshraghav** [comment]
Actually i had exams, so ic ould not work on this issue. Can i still work on it. @siv2r

**Comment by siv2r** [comment]
@jugeshraghav Sure! There is no time constraint :)
