### ISSUE TITLE
UI changes in the sign up page

### ISSUE THREAD

**Issue by tanya070820** [siv2r/kidney-exchange#306]
### Can you give some suggestions?

If there are multiple solutions, please present each one separately.

Save comparisons for the very end.

**Comment by siv2r** [comment]
@tanya070820 Sure, go ahead!
What changes are you planning? Also, make sure it aligns with the theme of the website (red-black, blue-black colors, etc)
Fee free to ask for help/doubts in the discord group

**Comment by riasenpai** [comment]
@tanya070820 any updates?
