### ISSUE TITLE
Wrap homepage content in a box and add transition

### ISSUE THREAD

**Issue by supzi-del** [siv2r/kidney-exchange#307]
### Can you please describe the problem to be solved?

The description of the project on the homepage looks blended into the background. 

### Can you give some suggestions?

This can be solved by adding an opaque background and add some scale transition for some depth.

Like these changes below
https://user-images.githubusercontent.com/78655439/122101892-76197a80-ce32-11eb-9006-1b9d149913ff.mp4

I would like to work on this.

**Comment by siv2r** [comment]
@supzi-del This looks interesting!
Also, you are talking about the new homepage, right? The homepage of deployed version (shown in the video) is old.

**Comment by supzi-del** [comment]
> @supzi-del This looks interesting!
> Also, you are talking about the new homepage, right? The homepage of deployed version (shown in the video) is old.

Can you send me a link to the new version?

**Comment by supzi-del** [comment]
Also I'm working on it under LGM SOC

**Comment by siv2r** [comment]
> > @supzi-del This looks interesting!
> > Also, you are talking about the new homepage. The homepage of deployed version (shown in the video) is old.
> 
> Can you send me a link to the new version?

Unfortunately, there is no deployed version of the new release. If you are working on the frontend alone, you can clone this repo and run it using docker in your local machine to see the current version.

**Comment by siv2r** [comment]
> you can clone this repo and run it using docker in your local machine to see the current version.

The steps for this is mention in Method 2 of the [build documentation](./docs/build.md).

**Comment by supzi-del** [comment]
Ok so where should I change the code(which file)?

**Comment by siv2r** [comment]
Index.php, in the root folder

**Comment by supzi-del** [comment]
> > you can clone this repo and run it using docker in your local machine to see the current version.
> 
> The steps for this is mention in [Method 2](https://github.com/siv2r/kidney-exchange/blob/master/docs/build.md#method-2-through-docker) of the build documentation.

I'm not able to view the new page..

**Comment by siv2r** [comment]
Can you tell me the exact error that you are getting? Or the problem that
you face?

**Comment by supzi-del** [comment]
![image](https://user-images.githubusercontent.com/78655439/122506062-2fd33f80-d01b-11eb-8c64-c284730d53e3.png)
Actually, I'm not able to get started with docker so...

**Comment by siv2r** [comment]
@supzi-del Sorry for the late reply. I didn't keep track of our conversation. Are you still interested in working on this issue?

You need to use `docker-compose` to run it. Also, do ask for doubts/help in the discord server (link in readme). You will get a reply over there immediately.

**Comment by siv2r** [comment]
Closing the issue due to inactivity.
@supzi-del feel free to send a PR when you get the time :)
