### ISSUE TITLE
`all-contributor` method to recognize contributors 

### ISSUE THREAD

**Issue by siv2r** [siv2r/kidney-exchange#308]
### Can you please describe the problem to be solved?
Better contributor recognition in the README

### Can you give some suggestions?

Follow the [all-contributors](https://github.com/all-contributors/all-contributors) method to recognize contributors
This is already implemented in the p5.js project using this [method](https://github.com/processing/p5.js/issues/2309). You can follow the same thing

**Comment by jayant766** [comment]
please assign it to me under LGM-SOC'21

**Comment by siv2r** [comment]
Assigned!
@jayant766, feel free to ask for doubts/help in the discord server.

**Comment by siv2r** [comment]
More info here: https://github.com/processing/p5.js?files=1#contributors

**Comment by siv2r** [comment]
@Sukriti-sood the pr #325 has done some progress regarding this issue. The implementation with incorrect since they hard-coded all the contributor's names to the readme file instead of creating a separate file like [this](https://github.com/processing/p5.js/blob/main/.all-contributorsrc). Creating a separate file will make the addition of new contributors to this project easier.

**Comment by swathi-469** [comment]
can I work on it and make a separate file and beginner-friendly along with images
