### ISSUE TITLE
Add Program Section in readme.md

### ISSUE THREAD

**Issue by ishitakapoor26** [siv2r/kidney-exchange#310]
Add Program Section which will represent that this project is a part of LGM-SOC'21

**Comment by ishitakapoor26** [comment]
@siv2r pls assign this issue to me.

**Comment by jayant766** [comment]
please assign it to me under LGM-SOC'21

**Comment by riasenpai** [comment]
@siv2r what do you think about this issue?

**Comment by siv2r** [comment]
@riasenpai @ishitakapoor26 This is not necessary.

**Comment by riasenpai** [comment]
@ishitakapoor26 you can work on some other issue!
