### ISSUE TITLE
Add LGM-SOC'21 score card in readme.md

### ISSUE THREAD

**Issue by ishitakapoor26** [siv2r/kidney-exchange#311]
Add LGM-SOC'21 score card in readme.md

**Comment by ishitakapoor26** [comment]
@siv2r

**Comment by ishitakapoor26** [comment]
Like this 
![score card](https://user-images.githubusercontent.com/78542333/122352859-1e335e80-cf6d-11eb-96cf-9a3fed92dd1b.PNG)

**Comment by riasenpai** [comment]
I am not sure that a score card is necessary in readme.md. @siv2r will let you know about this.

**Comment by siv2r** [comment]
@ishitakapoor26 This is not required.

**Comment by riasenpai** [comment]
@ishitakapoor26 you can work on some other issue!
