### ISSUE TITLE
Want to add a logo 

### ISSUE THREAD

**Issue by tjanhvi** [siv2r/kidney-exchange#312]
Want to add a logo for the heading "kidney exchange"

**Comment by tjanhvi** [comment]
okay :)
please assign me this issue

**Comment by riasenpai** [comment]
ok where would the logo be?

**Comment by siv2r** [comment]
@tj

**Comment by tjanhvi** [comment]
> ok where would the logo be?

I made some samples....

**Comment by riasenpai** [comment]
@tjanhvi any updates about those samples?

**Comment by nandini040** [comment]
I would like to work on this issue can you assign me this issue @riasenpai

**Comment by siv2r** [comment]
@nandini040 Sure! Go ahead 👍

**Comment by nandini040** [comment]
![image](https://user-images.githubusercontent.com/68437129/130036733-cf49966d-9f13-4a6b-8d92-2224cd79c73a.png)

This is the logo sample is it fine? or i should make some changes? @siv2r
