### ISSUE TITLE
Add a copyright design

### ISSUE THREAD

**Issue by tjanhvi** [siv2r/kidney-exchange#313]
Please assign me this issue

**Comment by siv2r** [comment]
@tjanhvi What exactly do you mean by copyright design? Can you elaborate your idea?

**Comment by tjanhvi** [comment]
This one is just an example and I will make this called a copyright design that I will place at the bottom of the website.
![image](https://user-images.githubusercontent.com/78703730/122571674-992e6f00-d06a-11eb-9da9-409ab0d949ed.png)

**Comment by tjanhvi** [comment]
I will do for this website then I will send you.

**Comment by siv2r** [comment]
@tjanhvi Sure!

**Comment by riasenpai** [comment]
@tjanhvi any updates?
