### ISSUE TITLE
add more badges to README.md file

### ISSUE THREAD

**Issue by Umesh-01** [siv2r/kidney-exchange#314]
### Can you please describe the problem to be solved?

add more badges to the top of readme.md file, since the badges will be colorful and more attractive at the top of README.md file than the text the users will like it and it will also help them to navigate to different sections/ webpages like PRs, issues, contributors, etc.

### Can you give some suggestions?
I will add some more badges so that the README.md file will look more attractive and awesome. And also I will align them all to the center.

### Screenshots (present)
I want to add more badges here

![image](https://user-images.githubusercontent.com/83420185/122445741-772be280-cfbf-11eb-9ae7-78a6ae7e203d.png)

**Comment by Umesh-01** [comment]
@siv2r Should I do these changes sir??

**Comment by siv2r** [comment]
Sure, go ahead! Also, no need to call me sir.

**Comment by Umesh-01** [comment]
@siv2r @riasenpai pls assign some labels for **LGMSOC** and check the PR, merge if everything is fine 🙂
