### ISSUE TITLE
database connection

### ISSUE THREAD

**Issue by Sukriti-sood** [siv2r/kidney-exchange#317]
## Problem
While connectiing to the database wveryone running the project locally need to change username and password and accidently most of the contributors push code with their credentials .

## Solution

We can have a sample.env which include username and password field and every time when user runs the projects locally will create .env files and copy the data from sample.env and respective value of username and password , hence while pushing changes credentials remains safe 

Will add respective instructions in Documentation.

**Comment by siv2r** [comment]
@Sukriti-sood This issue is very interesting!
