### ISSUE TITLE
Modifying the CSS of login and register page.

### ISSUE THREAD

**Issue by Swarga-codes** [siv2r/kidney-exchange#320]
### Can you please describe the problem to be solved?
I would like to modify the CSS of the login page and register page or you can say redesign the form for a better Login & register UI.

### Can you give some suggestions?

If there are multiple solutions, please present each one separately.

Save comparisons for the very end.

**Comment by siv2r** [comment]
@Swarga-codes Sure! Please go ahead!
Also, make sure that the color fits with the overall theme of the website. Ideally, the color combo used of red-black, blue-black. You can also explore other variants.
Feel free to ask for help/doubts in the discord group

**Comment by Swarga-codes** [comment]
> @Swarga-codes Sure! Please go ahead!
> Also, make sure that the color fits with the overall theme of the website. Ideally, the color combo used of red-black, blue-black. You can also explore other variants.
> Feel free to ask for help/doubts in the discord group

I have a small doubt like I used to view the website throught the html files using live server in VScode now , how should I view the website using the php file any extension which I should download in my VSCode (Ps: I can see the source code but I cannot view the website using the live server(Go Live) in Vscode. Please help!
