### ISSUE TITLE
Add show password option to login signup page

### ISSUE THREAD

**Issue by ayushseth07** [siv2r/kidney-exchange#324]
In the login and signup page inside the password field we can add and eye icon which when clicked shows the password

### Can you give some suggestions?

If there are multiple solutions, please present each one separately.

Save comparisons for the very end.

**Comment by ayushseth07** [comment]
Can i work on this issue?

**Comment by siv2r** [comment]
@ayushseth07 Sure, go ahead!
There is already a checkbox outside to make the password visible. Instead of that, you can implement your idea.

Feel free to ask for doubts/help in your discord server.
