### ISSUE TITLE
Mobile responsive

### ISSUE THREAD

**Issue by nitishapiplani** [siv2r/kidney-exchange#328]
Make page responsive for mobile so that user can use it on mobile
![Screenshot_2021-06-30-17-00-12-91_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/83905949/123953593-03c5a000-d9c5-11eb-9858-628f800c975f.jpg)

**Comment by siv2r** [comment]
@nitishapiplani The deployed version of the website is not updated yet.

This issue for the homepage is fixed. You can clone the repo and run it in your local machine to observe the change. Also, feel free to open new issues if you find any.

**Comment by nitishapiplani** [comment]
okk sure

**Comment by riasenpai** [comment]
@nitishapiplani any updates?

**Comment by nitishapiplani** [comment]
You said issue is resolved

**Comment by riasenpai** [comment]
Ok cool closing this. Thanks!
