### ISSUE TITLE
Create a bot to add contributors to the readme

### ISSUE THREAD

**Issue by siv2r** [siv2r/kidney-exchange#329]
### Can you please describe the problem to be solved?
This project follows the `all-contributors` specifications for recognizing contributors. It would be great if there is a bot to add new people to the contributor's list in the readme.

### Can you give some suggestions?

This has already been implemented in the p5.js project. You can simply use their code instead of creating the bot from scratch.
Find their implementation here: https://github.com/processing/p5.js?files=1#contributors

**Comment by Sukriti-sood** [comment]
@siv2r Is it not same as #308

**Comment by riasenpai** [comment]
> @siv2r Is it not same as #308

adding the contributors to the readme using a bot is similar to the issue you mentioned. I did find a bot https://allcontributors.org/ . Maybe this will help.

**Comment by siv2r** [comment]
> @siv2r Is it not the same as #308

It is not the same. Ideally, a contributor has to open a PR (adding their info to .allconributors file) for adding them to the readme file. In this, we will make a bot to create a PR if a contributor opens an issue or comments with the text: `@all-contributors please add @YOUR-USERNAME for THING(S)`

**Comment by Sukriti-sood** [comment]
@all-contributors please add @siv2r  for code

**Comment by Sukriti-sood** [comment]
@all-contributors please add @siv2r  for  documentation

**Comment by Sukriti-sood** [comment]
@all-contributors please add @siv2r for maintenance

**Comment by Sukriti-sood** [comment]
@all-contributors please add @arpit456jain r for code
@all-contributors please add @arpit456jain  for documentation

**Comment by Sukriti-sood** [comment]
@all-contributors please add @arpit456jain for code and doc

**Comment by Sukriti-sood** [comment]
@all-contributors please add @madihamallick  for doc and code

**Comment by Sukriti-sood** [comment]
@all-contributors please add @Spurthi7768  for doc and code

**Comment by Sukriti-sood** [comment]
@all-contributors please add @darpankhanna for doc

**Comment by Sukriti-sood** [comment]
@all-contributors please add @subhangi2731  for doc

**Comment by Sukriti-sood** [comment]
@all-contributors please add @96RadhikaJadhav  for code

**Comment by Sukriti-sood** [comment]
@all-contributors please add @khareyash05  for doc

**Comment by Sukriti-sood** [comment]
@all-contributors please add @thalesagapito  for code

**Comment by Sukriti-sood** [comment]
@all-contributors please add @rohan-kulkarni-25  for doc

**Comment by Sukriti-sood** [comment]
@all-contributors please add @AshuKV  for doc and code

**Comment by Sukriti-sood** [comment]
@all-contributors please add @Shania99  for  code

**Comment by Sukriti-sood** [comment]
@all-contributors please add @arpit456jain for code and doc

**Comment by rohan-kulkarni-25** [comment]
You can use my repository in that it will fetch all Contributors automatically in seperate page !

**Comment by Sukriti-sood** [comment]
@all-contributors please add @Itashamodi  for doc

**Comment by Sukriti-sood** [comment]
@all-contributors please add @kanchi12P  for  doc

**Comment by Sukriti-sood** [comment]
@all-contributors please add @jwalapc  for code

**Comment by Sukriti-sood** [comment]
@all-contributors please add @aditi1403 for doc

**Comment by Sukriti-sood** [comment]
@all-contributors please add @hardikvarshney  for doc and design

**Comment by Sukriti-sood** [comment]
@all-contributors please add @Swarga-codes  for code

**Comment by Sukriti-sood** [comment]
@all-contributors please add @Subhangini  for doc

**Comment by Sukriti-sood** [comment]
@all-contributors please add @Shaishav0507  for  doc

**Comment by Sukriti-sood** [comment]
@all-contributors please add @Hjaelp for code

**Comment by Sukriti-sood** [comment]
@all-contributors please add @devanshi-code  for doc

**Comment by Sukriti-sood** [comment]
@all-contributors please add @nisha331  for doc

**Comment by Sukriti-sood** [comment]
@all-contributors please add @889-dj  for doc

**Comment by Sukriti-sood** [comment]
@all-contributors please add @kumarshobhit  for code

**Comment by Sukriti-sood** [comment]
@all-contributors please add @Umesh-01  for doc

**Comment by Sukriti-sood** [comment]
@all-contributors please add @nitinshukla413  for code

**Comment by Sukriti-sood** [comment]
@all-contributors please add @nityaak5  for doc

**Comment by Sukriti-sood** [comment]
@all-contributors please add @ayushseth07 for code

**Comment by Sukriti-sood** [comment]
@all-contributors please add @M2kishore  for doc

**Comment by Sukriti-sood** [comment]
@all-contributors please add @6D-pixel  for code

**Comment by Sukriti-sood** [comment]
@all-contributors please add @nandini040  for doc

**Comment by Sukriti-sood** [comment]
@all-contributors please add @Shania99 for code

**Comment by Sukriti-sood** [comment]
@all-contributors please add @Shania99 for code

**Comment by Sukriti-sood** [comment]
@all-contributors add @Itashamodi as a contributor for doc

**Comment by Sukriti-sood** [comment]
@all-contributors add @kanchi12P as a contributor for doc

**Comment by Sukriti-sood** [comment]
@all-contributors add @jwalapc as a contributor for code

**Comment by Sukriti-sood** [comment]
@all-contributors add @aditi1403 as a contributor for doc

**Comment by Sukriti-sood** [comment]
@all-contributors add @hardikvarshney as a contributor for doc, design

**Comment by Sukriti-sood** [comment]
@allcontributors add @Swarga-codes as a contributor for code

**Comment by Sukriti-sood** [comment]
@allcontributors add @Subhangini as a contributor for doc

**Comment by Sukriti-sood** [comment]
@allcontributors add @Shaishav0507 as a contributor for doc

**Comment by Sukriti-sood** [comment]
@allcontributors add @Hjaelp as a contributor for code

**Comment by Sukriti-sood** [comment]
@allcontributors add @devanshi-code as a contributor for doc

**Comment by Sukriti-sood** [comment]
@allcontributors add @nisha331 as a contributor for doc

**Comment by Sukriti-sood** [comment]
@allcontributors add @889-dj as a contributor for doc

**Comment by Sukriti-sood** [comment]
@allcontributors add @kumarshobhit as a contributor for code

**Comment by Sukriti-sood** [comment]
@allcontributors add @Umesh-01 as a contributor for doc

**Comment by Sukriti-sood** [comment]
@allcontributors add @nitinshukla413 as a contributor for code

**Comment by Sukriti-sood** [comment]
@allcontributors add @nityaak5 as a contributor for doc

**Comment by Sukriti-sood** [comment]
@allcontributors add ayushseth07 as a contributor for code

**Comment by Sukriti-sood** [comment]
@allcontributors add M2kishore as a contributor for doc

**Comment by Sukriti-sood** [comment]
@allcontributors add 6D-pixel as a contributor for code

**Comment by Sukriti-sood** [comment]
@allcontributors add nandini040 as a contributor for doc

**Comment by AlapanDas** [comment]
I can try implementing this feature, if it's not yet done by someone else
@siv2r Please assign this issue to me 
@GSSOC 22'

**Comment by siv2r** [comment]
@AlapanDas, sure go ahead!

**Comment by Sukriti-sood** [comment]
@siv2r I think, thia issue feature is already implemented by me.... , it can be closed

**Comment by siv2r** [comment]
Closing this issue since this feature was already implemented
