### ISSUE TITLE
Width bug in Overview page

### ISSUE THREAD

**Issue by siv2r** [siv2r/kidney-exchange#33]
Table contents are displayed in two lines if the ID is long :( on the dataOverview.php

**Comment by sahildotexe** [comment]
Hey !! I am a participant of GSSOC'21 , can you assign this issue to me?

**Comment by siv2r** [comment]
You can start working on this issue :)

**Comment by araiz-1999** [comment]
Intrested, can it be assigned to me ?

**Comment by siv2r** [comment]
@araiz-1999 Sure!! you can start working on it :)

**Comment by araiz-1999** [comment]
Hey whats issue #33 ? Which has been assigned to me.

**Comment by arpit456jain** [comment]
I will give it a try may be i can solve this

**Comment by arpit456jain** [comment]
<img width="960" alt="data" src="https://user-images.githubusercontent.com/55352601/118223678-70312200-b49f-11eb-852d-d5ba3bf5824a.png">

**Comment by arpit456jain** [comment]
I have done some changes and here is the result if id is long than this then it will surely take 2 lines

**Comment by arpit456jain** [comment]
![screencapture-localhost-kidney-exchange-pages-dataOverview-php-2021-05-14-10_45_58](https://user-images.githubusercontent.com/55352601/118224848-8e981d00-b4a1-11eb-8a52-0ee7eb01d303.png)

for phone view i have to hide last 3 columns its not possible to display 6 cols in small screens ..
hope you understand :)

**Comment by arpit456jain** [comment]
@siv2r I am creating another issue for responsiveness  of this page will commit these changes in that PR
