### ISSUE TITLE
CONTRIBUTION GUIDELINES

### ISSUE THREAD

**Issue by swathi-469** [siv2r/kidney-exchange#331]
I would like to add a contribution guidelines for the beginners in Open source

**Comment by siv2r** [comment]
@swathi-469 Sure! There is already a document (in the README) for the first-time opensource contributors. You can improve it :)
Also, feel free to ask for help/doubts in our discord server (link in README)

**Comment by swathi-469** [comment]
yeah mam but a lot of things are going around README, so I would like to make a separate file for guidelines

**Comment by riasenpai** [comment]
@swathi-469 any updates??

**Comment by swathi-469** [comment]
yeah mam but a lot of things are going around README, so I would like to make a separate file for guidelines as part of LGM-SOC21 ... I have asked you about it that's why I am waiting mam
