### ISSUE TITLE
Imporve UI

### ISSUE THREAD

**Issue by AshutoshDash1999** [siv2r/kidney-exchange#396]
- Want to add glassmorphic UI as text to background contrast is not good.

Can you please asign this issue to me?

**Comment by ykstech** [comment]
i would like to work on this issue under Gssoc ...

**Comment by AshutoshDash1999** [comment]
@ykstech i'm also a contributor but i don't want to work as the project in PHP and I couldn't understand it 😅
you can work on it by reopening :)
