### ISSUE TITLE
Mobile view of website

### ISSUE THREAD

**Issue by schmelto** [siv2r/kidney-exchange#44]
![Screenshot_20210219_221934_com.android.chrome~2.jpg](https://user-images.githubusercontent.com/30869493/108562786-b04d9200-7300-11eb-9a4e-7970f6a75447.jpg)

**Comment by siv2r** [comment]
Hi @schmelto, 

There is already an issue opened (#22 ) related to the mobile-friendly nature of the navbar. Wouldn't this come under the same category? 

Thanks for adding the screenshot :)

**Comment by schmelto** [comment]
Hey @siv2r yeah same category. Sorry didn't go through all issues :)
