### ISSUE TITLE
fix background of input fields after validation

### ISSUE THREAD

**Issue by siv2r** [siv2r/kidney-exchange#5]
The following input fields' background color does not change when the entered value is invalid.
1. Comorbid conditions (in the patient registration form)
2. Pre-existing illness (in the donor registration form)
3. HLA Antigens: A, B, DR (in both patient and donor registration form)

**Examples:**

![Screenshot from 2020-10-03 17-24-28](https://user-images.githubusercontent.com/56887198/94991434-c13f7600-05a0-11eb-981c-357883d01599.png)

**Helpful Information:**
1. All these input fields are multi-select type hence select2 plugin was used to beautify it.
2. Select2 changes the default input HTML tag into two HTML tags hence the normal background color changes that are applied to other fields are not working here.

**Comment by thalesagapito** [comment]
I could help out with this

**Comment by siv2r** [comment]
Sure, go ahead! If you need anything let me know

**Comment by thalesagapito** [comment]
The PR is open at #7, I also created a Dockerfile in the root of the project to run it without needing PHP installed. Would you be interested in adding it to the project?

**Comment by siv2r** [comment]
Yes, I am interested.
