### ISSUE TITLE
Github Action to format .py files with `black`

### ISSUE THREAD

**Issue by siv2r** [siv2r/kidney-exchange#55]

**Comment by subhangi2731** [comment]
can you please assign this issue to me?

**Comment by siv2r** [comment]
@subhangi2731 Sure! You can start working on it. Also, read the contributors guidelines before starting to contribute :)

**Comment by siv2r** [comment]
@Sukriti-sood I tried implementing this here: https://github.com/siv2r/kidney-exchange/blob/master/.github/workflows/autoblack.yml
But, it did not work as expected.

**Comment by Sukriti-sood** [comment]
@siv2r  I found [this](https://github.com/marketplace/actions/black-code-formatter) will try to implement this

**Comment by Sukriti-sood** [comment]
> @Sukriti-sood I tried implementing this here: https://github.com/siv2r/kidney-exchange/blob/master/.github/workflows/autoblack.yml
> But, it did not work as expected.

@siv2r  ,I think [black-action](https://github.com/lgeiger/black-action)  uses different workflows for push and pull request that may be the reason.

**Comment by siv2r** [comment]
> I think [black-action](https://github.com/lgeiger/black-action) uses different workflows for push and pull request that may be the reason.

Might be. You can use a new approach if mine was wrong.
