### ISSUE TITLE
add guidelines.md

### ISSUE THREAD

**Issue by khareyash05** [siv2r/kidney-exchange#58]
Hi! I would like to add contributing.md to the repo which states on how to clone and fork the repo,how to add ,create and push a repo,squash commits,rebase your feature branch ,how to update forked repo as well as local repo to the changes made in upstream.
I would like to work on this under GSSOC'21.

**Comment by siv2r** [comment]
That's great to hear! 
There is already a file named `CONTRIBUTING.md` in the repo. You can either add this as a subtopic like "How to create a pull request?" in `CONTRIBUTING.md` or create a new file with an appropriate name and link this in the `README.md`.

**Comment by khareyash05** [comment]
@siv2r sure

**Comment by siv2r** [comment]
@khareyash05 can you create a new file instead of adding it as a subsection in `CONTRIBUTING.md`?

**Comment by khareyash05** [comment]
> @khareyash05 can you create a new file instead of adding it as a subsection in `CONTRIBUTING.md`? 

Sure I will do that could you pls suggest me with a name of the file? 
I have one name in my mind - guidelines?
