### ISSUE TITLE
Add background color for invalid radio labels

### ISSUE THREAD

**Issue by siv2r** [siv2r/kidney-exchange#6]
Currently, there are no background colors for the radio button labels (i.e, positive, negative)

**Example:**
![Screenshot from 2020-10-03 17-24-28 (1)](https://user-images.githubusercontent.com/56887198/94998894-f664bc00-05d2-11eb-8785-1e8eef99a9b0.jpg)

**Instructions**
1. Do not create a new script file or CSS file
2. Add the screenshots of the form after the fix in your pull request
3. Add #fff0f4 as the background-color

**Helpful Information**
1. In the **css/form-styles.css** you will find the below code which is used to style the custom error class added to invalid input fields.

```
.has-error{
  border: 1px solid #c51244;
  background-color: #fff0f4; 
}

.help-block{
  color: #c51244;
  font-size: 18px;
  display: inline-block;
  width: 60%;
}
```
2. These classes are added to the invalid input fields by the validation() function present in **scripts/reg-form.js**

**Comment by paresh27** [comment]
Can I help you with this?

**Comment by slshashika** [comment]
I would like to fix these issue

**Comment by siv2r** [comment]
@paresh27  I have added some helpful information. Please let me know if you need anything else.

**Comment by paresh27** [comment]
No that's enough, let me start it.

**Comment by RituCs** [comment]
Hello , I would like to contribute on this issue.Please assign me .

**Comment by sahildotexe** [comment]
Hey !! I am a participant of GSSOC'21 , can you assign this issue to me?

**Comment by SurbhiRathi23** [comment]
Hi, I want to work on this issue. Can you please assign this issue to me?

**Comment by siv2r** [comment]
@RituCs Sure! Go ahead!

**Comment by araiz-1999** [comment]
I would like to take a shot at this...

**Comment by siv2r** [comment]
@araiz-1999 please work only on one issue at a time. You can move on to another if you have completed one :)

**Comment by lakshita15** [comment]
I'am gssoc participant 
I would like to work on this issue. I will submit before due date with fantastic work.

**Comment by pyash99** [comment]
I am a GSSOC'21 participant can you assign me this issue.

**Comment by siv2r** [comment]
@pyash99 you can start working on this issue no need to wait for the issue to be assigned to you. I stopped assigning issues since ppl started spamming.

**Comment by jwalapc** [comment]
I had made some changes will this work because if we want to change the color of the radio-buttons only we need to add more elements and css.
![image](https://user-images.githubusercontent.com/59509045/121713513-94157100-cafa-11eb-9464-c8d15265b643.png)
