### ISSUE TITLE
Tech Stack Update ( LOGO add ) 

### ISSUE THREAD

**Issue by rohank2502** [siv2r/kidney-exchange#65]
I will like to add tech stack logo used in our project this will make our project attractive !! Will start to work on this issue as soon as i get assigned !!

**Comment by siv2r** [comment]
@rohank2502 Sure! You can start working on it!! Also, read the guideline before starting to contribute :)

**Comment by rohank2502** [comment]
>  on it!! Also, read the guideline before starting to contribute :)

Yes sure I will read !!
