### ISSUE TITLE
Adding Contributor section in readme  ( Automatically )

### ISSUE THREAD

**Issue by rohank2502** [siv2r/kidney-exchange#66]
I will like to add a feature this will update contributor list in read me automatically !! Will start to work on this issue as soon as i get assigend !!

**Comment by siv2r** [comment]
@rohank2502 Sure!! You can start working on it.

**Comment by rohank2502** [comment]
> 
> 
> @rohank2502 Sure!! You can start working on it.

Thanks Please assign this issue !!

**Comment by siv2r** [comment]
> > @rohank2502 Sure!! You can start working on it.
> 
> Thanks Please assign this issue !!

I stopped assigning issues since everyone started spamming the issue page. More details are mentioned in the guidelines document which I asked you to read in #65 :)

**Comment by rohank2502** [comment]
Ok i will start work !!
