### ISSUE TITLE
Reduce the age input in patient and donor form

### ISSUE THREAD

**Issue by siv2r** [siv2r/kidney-exchange#69]
While filling the `patient` form under the `register` menu, the user can enter any date of birth for the patient and donor. For Example, he can `01/01/1920`, which is not recommended since having a donor of age `102` is impossible :sweat_smile: 

**_Note_** Do not add an error msg for this. Just limit the input which the user can enter for the date of birth field.

**Changes required**
- Restrict the patient age (0 <= age <= 80)
- Restrict the donor age (18 <= age <= 80)

**Comment by Spurthi7768** [comment]
@siv2r  Can I work on this issue? Also if yes then can I create a new validation method for max age?

**Comment by siv2r** [comment]
Sure!! Go ahead :+1: 
It would be better to limit the user's input instead of creating an additional validation method.

**Comment by Spurthi7768** [comment]
@siv2r I had a doubt..so for limiting user input do we have to consider that the patient is of age 80 by 2021? What if someone wants to use the platform in 2030?

**Comment by siv2r** [comment]
Good observation!! I did not think about this. Then you can allow users to enter the year (in the date of birth field) only after 1950.

**Comment by amritakesh** [comment]
hello
i'm taking part in gssoc 2021. And i would like work on this issue, will you please assign this to me?

**Comment by siv2r** [comment]
@amritakesh, I believe @Spurthi7768 is working on it. If @Spurthi7768 is willing, both of you can collaborate to solve this issue, or you can try taking a look at other issues.

Also, do not worry about gssoc points. I will make sure both of you get it if you plan to collaborate :)

**Comment by Kavs-123** [comment]
Hey @siv2r!
Can I work on this issue?

**Comment by siv2r** [comment]
@Kavs-123 There is already a PR for this #80 
If you can come up with a better approach, you can start working on it :)

**Comment by Kavs-123** [comment]
Ohk @siv2r  :)
