### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by kanchi12P** [siv2r/kidney-exchange#72]
I would like to add some graphics in the readme file to make it more attractive and graphics that convey the project moto
And will try to modify the font and colors
and add some small icons
please assign it to me.

**Comment by siv2r** [comment]
@kanchi12P you can start working on it. Can elaborate abt the changes? Also, read the community guidelines before starting to contribute.

**Comment by kanchi12P** [comment]
I will add some images which explain the kidney exchange program.

**Comment by kanchi12P** [comment]
And will try to modify the font and colors 
and add some small icons

**Comment by kanchi12P** [comment]
Is the issue assigned?
Please tell

**Comment by siv2r** [comment]
@kanchi12P Do not wait for an issue to be assigned to you. I stopped assigning issues since ppl started spamming. 
This is clearly mentioned on the community guidelines, which is why I asked you to read it first :)

**Comment by siv2r** [comment]
> And will try to modify the font and colors
> and add some small icons

Please add these details to the description of this issue.

**Comment by siv2r** [comment]
Closing this issue since the necessary PR was merged.
