### ISSUE TITLE
Pull request template and Code of conduct missing 

### ISSUE THREAD

**Issue by nandini040** [siv2r/kidney-exchange#83]

**Comment by siv2r** [comment]
I think a PR template will suffice. I have already added guidelines document

**Comment by Subhangini** [comment]
I would like to work on this as a gssoc Participant

**Comment by siv2r** [comment]
@Subhangini Sure!! you can start working on this :)

**Comment by Subhangini** [comment]
Please add `level` and `gssoc` label
