### ISSUE TITLE
Fix the startsCapital jQuery method 

### ISSUE THREAD

**Issue by siv2r** [siv2r/kidney-exchange#9]
**Instructions**
1. Do not create a new script file or CSS file
2. Add the screenshots of the form after the fix in your pull request

The code below is in **scripts/reg-form.js**. This is a custom jquery validation method that forces the user to start their name with a capital letter.

```
    $.validator.addMethod( "startsCapital", function( value, element ) {
      return this.optional( element ) || /^[A-Z]/i.test( value );
    }, "Please start your name with a capital letter" );
```
That method is called here (in **scripts/reg-form.js**)
```
        r_fname: {
          required: true,
          nowhitespace: true,
          lettersonly: true,
          startsCapital: true
        },
```

The is no error message shown in the form when the user enters a name starting with a small letter.

**Example:**
![Screenshot from 2020-10-04 00-18-25](https://user-images.githubusercontent.com/56887198/94999526-8c9ae100-05d7-11eb-99e5-264dc5612d09.jpg)

**Comment by NileshChoudhary111** [comment]
Hi Buddy,

Can you assign this to me?

**Comment by Sourav59580** [comment]
Hello sir, 
I have solved this issue, please check my pull request.

**Comment by Sourav59580** [comment]
#10  the startsCapital jQuery method #10
