### ISSUE TITLE
Missing! Brand logo of the website.

### ISSUE THREAD

**Issue by hardikvarshney** [siv2r/kidney-exchange#94]

**Comment by siv2r** [comment]
Currently there is no logo decided. If you have some ideas, you can open a PR :)

**Comment by hardikvarshney** [comment]
Please mention the level of this issue. And assign this issue to me.

**Comment by hardikvarshney** [comment]
![logo1](https://user-images.githubusercontent.com/76947310/113969334-7144b300-9852-11eb-9889-80700f9f1013.png)
I have chosen this logo for our website. Can I go ahead with this logo.

**Comment by siv2r** [comment]
Hey, this looks good. Can you come up with something with a darker theme? (preferably red, black, blue also other colors if you think they look good)

I am asking for a darker theme since the look of the whole website is based on it. Also, no need for the name "Kidney Exchange" to be present. You can keep the logo **minimalist** and somewhat relevant.

**Comment by siv2r** [comment]
Minimalist designs looks like [this](https://www.google.com/search?q=minimalist+wallpaper&tbm=isch&ved=2ahUKEwiAlICPye7vAhUXXX0KHQHgBpMQ2-cCegQIABAA&oq=minimalist+wal&gs_lcp=CgNpbWcQARgAMgQIIxAnMgUIABCxAzIFCAAQsQMyAggAMgIIADIFCAAQsQMyAggAMgIIADICCAAyAggAUKcIWJYUYMEaaABwAHgAgAFniAGVBpIBAzguMZgBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=nOxuYIDWApe69QOBwJuYCQ&bih=715&biw=1386)

**Comment by hardikvarshney** [comment]
Okay.

**Comment by hardikvarshney** [comment]
![logo3](https://user-images.githubusercontent.com/76947310/114033816-37e46580-989b-11eb-86dd-4ae513905bf2.png)
What about this????

**Comment by siv2r** [comment]
Looks amazing! You can create a PR adding this to the readme.

**Comment by hardikvarshney** [comment]
@siv2r I have to remove this logo from readme and add new one OR only add new logo??
![Screenshot (78)](https://user-images.githubusercontent.com/76947310/114063668-7cc9c580-98b6-11eb-964d-97778eb8e80c.png)

**Comment by siv2r** [comment]
No, that is not the logo so, do not remove it. You can add your logo besides the heading "Kidney Exchange"

**Comment by hardikvarshney** [comment]
Okay
