### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by saimanoharhm** [siv2r/kidney-exchange#95]
I would like to work on landing page with better design and responsive page.  Could you pls assign this to me.  @siv2r

**Comment by siv2r** [comment]
Hi, what do u exactly mean by landing page? The homepage?

**Comment by saimanoharhm** [comment]
@siv2r Yes

**Comment by siv2r** [comment]
Sure, go ahead :)
You can take a look at this #73 for starters.

**Comment by saimanoharhm** [comment]
![Copy of Health flyer - Made with PosterMyWall](https://user-images.githubusercontent.com/72253236/114138560-70cc1b00-992b-11eb-804e-a7189b73fba7.jpg)

@siv2r How's this background image. If it fine then I will proceed with the code.

**Comment by siv2r** [comment]
Did you take a look at #73? This website has a dark theme so, a light theme is not preferred. 

Also, if the wallpaper is minimalist it will be better. Google "minimalist wallpapers" to get idea about their design.

**Comment by saimanoharhm** [comment]
@siv2r  I will create one dark mode button at right side corner.  When user clicks the  dark mode then the website change it into black color.  Will that be fine.

**Comment by saimanoharhm** [comment]
> Did you take a look at #73? This website has a dark theme so, a light theme is not preferred.
@siv2r Yes I have seen that .

**Comment by saimanoharhm** [comment]
> @siv2r I will create one dark mode button at right side corner. When user clicks the dark mode then the website change it into black color. Will that be fine.

@siv2r  I will use same design which I shared you above but it will change it dark mode if user needed by clicking the button.

**Comment by siv2r** [comment]
> @siv2r  I will create one dark mode button at right side corner.  When user clicks the  dark mode then the website change it into black color.  Will that be fine.

This seems to a bit of overkill. Also, it will not be of much use since  it will change only the 'homepage' to darker theme.

A single minimalist background theme will suffice.

**Comment by saimanoharhm** [comment]
![Copy of Covid-19 Vaccination Program - Made with PosterMyWall](https://user-images.githubusercontent.com/72253236/114146888-bc83c200-9935-11eb-907e-ef3d906eb4f0.jpg)

@siv2r How's this thing. If it not fine. Could you pls share some examples like what you are expecting

**Comment by saimanoharhm** [comment]
@siv2r Could you pls whether should I proceed with it ot not

**Comment by siv2r** [comment]
Hey, This seem to have lot of wording in the corner and stuff so, don't use this

**Comment by siv2r** [comment]
Also, it is not necessary that it needs to be related to medical. It can be any simple theme. Like in the "minimalist background"

**Comment by saimanoharhm** [comment]
![Copy of Smoke Youtube Channel Art Banner Template - Made with PosterMyWall](https://user-images.githubusercontent.com/72253236/114229541-9beb5480-9995-11eb-97d9-659c4f621fe8.jpg)

























![Copy of R Black Sparkle - Made with PosterMyWall](https://user-images.githubusercontent.com/72253236/114229542-9d1c8180-9995-11eb-84ee-4409f93f3a6f.jpg)



Can I go with any of this @siv2r

**Comment by siv2r** [comment]
Those does not look good :(

**Comment by saimanoharhm** [comment]
@siv2r Ok. No problem.  I will work to make a page to responsive.

**Comment by saimanoharhm** [comment]
@siv2r I will make a responsive page.  Will that be fine I don't change the image but I will make it as responsive page.

**Comment by siv2r** [comment]
Sure, no worries :)
Also take your time tomdo things no need to hurry things up. It is important that you learn something new in this process.

**Comment by siv2r** [comment]
Closing this issue since, it is not required
