### ISSUE TITLE
[Gssoc'21] Show Password Button in Login/Signup

### ISSUE THREAD

**Issue by arpit456jain** [siv2r/kidney-exchange#99]
I want to add a Show Password Button in Login/Signup

**Comment by siv2r** [comment]
Sure!! Go ahead :)

**Comment by arpit456jain** [comment]
Ok

**Comment by arpit456jain** [comment]
Kindly assign me this issue and add labels of GSSoC'21

**Comment by arpit456jain** [comment]
@siv2r kindly review my PR and add the same labels to it.
